/**
 * pac.js — PAC(Proxy Auto-Config) 스크립트 생성기.
 *
 * 설계 원칙
 *  1) **ASCII 전용**: `chrome.proxy` 의 `pacScript.data` 는 ASCII 만 허용한다.
 *     주석 하나라도 한글이 섞이면 다음 오류로 거부된다.
 *       'pacScript.data' supports only ASCII code(encode URLs in Punycode format)
 *     그래서 아래 PAC 본문의 주석은 전부 영어이고, 주입 데이터는
 *     `toAsciiJson()` 으로 `\uXXXX` 이스케이프하며, 마지막에 검증까지 한다.
 *     한국어 설명은 이 파일의 JSDoc(=PAC 에 들어가지 않는 부분)에만 둔다.
 *  2) **fail-closed**: 프록시 토큰 뒤에 `; DIRECT` 폴백을 절대 붙이지 않는다.
 *     붙이면 프록시가 죽었을 때 조용히 실제(셀룰러) IP 로 나가버린다.
 *  3) **DNS 조회 금지**: PAC 안에서 dnsResolve()/isInNet(호스트명) 을 쓰지 않는다.
 *     이들은 로컬 DNS 조회를 유발해 지연을 만들고, 통신사 DNS 에 목적지를 노출한다.
 *     따라서 IP 판정은 리터럴 IP 에 대해서만 직접 파싱해서 수행한다.
 *  4) **PAC 본문은 ES5**: PAC 실행 환경의 문법 지원 범위를 가정하지 않는다.
 *
 * 배경: Chrome/Edge 는 GUI 로 HTTPS 프록시를 지정할 수 없고 PAC 의
 * "HTTPS host:port" 토큰으로만 지정할 수 있다. 그래서 fixed_servers 대신
 * pac_script 모드를 쓴다.
 */

import { PAC_TOKEN_BY_SCHEME } from './constants.js';
import { findNonAscii, hostPatternToAscii, hostToAscii, toAsciiJson } from './idn.js';

/**
 * 설정에서 PAC 프록시 토큰을 만든다. 예: `HTTPS proxy.example.com:443`
 *
 * 호스트가 국제화 도메인이면 Punycode 로 변환한다.
 *
 * @param {{scheme: string, host: string, port: number|string}} server
 * @returns {string}
 */
export function buildProxyToken(server) {
  const token = PAC_TOKEN_BY_SCHEME[server.scheme];
  if (!token) throw new Error(`지원하지 않는 스킴: ${server.scheme}`);
  return `${token} ${hostToAscii(server.host)}:${Number(server.port)}`;
}

/**
 * 호스트 패턴 목록을 정확 일치 / 접미사 일치로 분리한다.
 * `*.example.com` → 접미사 `.example.com` + 정확 일치 `example.com`
 *
 * @param {string[]} patterns
 * @returns {{exact: string[], suffix: string[]}}
 */
function splitHostPatterns(patterns) {
  const exact = new Set();
  const suffix = new Set();

  for (const raw of patterns ?? []) {
    const value = hostPatternToAscii(raw);
    if (!value) continue;

    if (value.startsWith('*.')) {
      const bare = value.slice(2);
      suffix.add(`.${bare}`);
      exact.add(bare); // *.local 은 local 자체도 우회하는 게 자연스럽다
    } else {
      exact.add(value);
    }
  }
  return { exact: [...exact], suffix: [...suffix] };
}

/**
 * CIDR 문자열을 [네트워크주소(uint32), 프리픽스길이] 로 변환한다.
 * @param {string[]} cidrs
 * @returns {Array<[number, number]>}
 */
function toNumericCidrs(cidrs) {
  const result = [];
  for (const raw of cidrs ?? []) {
    const [addr, prefixText] = String(raw).trim().split('/');
    const octets = addr.split('.').map(Number);
    if (octets.length !== 4 || octets.some((o) => !Number.isInteger(o) || o < 0 || o > 255)) {
      continue;
    }
    const prefix = Number(prefixText);
    if (!Number.isInteger(prefix) || prefix < 0 || prefix > 32) continue;

    const value =
      ((octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3]) >>> 0;
    const mask = prefix === 0 ? 0 : (0xffffffff << (32 - prefix)) >>> 0;
    result.push([(value & mask) >>> 0, prefix]);
  }
  return result;
}

/**
 * PAC 소스가 순수 ASCII 인지 검증한다. 아니면 위치까지 담아 예외를 던진다.
 *
 * `chrome.proxy.settings.set()` 이 거부하기 전에 우리가 먼저 잡아, 사용자에게
 * "어디가 문제인지" 알려주기 위한 함수다. (Chrome 의 오류 메시지는 위치를
 * 알려주지 않는다.)
 *
 * @param {string} source
 * @returns {string} 입력 그대로 (체이닝 편의)
 * @throws {Error} 비ASCII 문자가 있으면
 */
export function assertPacIsAscii(source) {
  const offender = findNonAscii(source);
  if (!offender) return source;

  const context = source.slice(
    Math.max(0, offender.index - 40),
    offender.index + 40,
  );
  throw new Error(
    `PAC 스크립트에 ASCII 가 아닌 문자가 있습니다: ${offender.char} ` +
      `(${offender.codePoint}, 위치 ${offender.index}). ` +
      `chrome.proxy 는 ASCII 만 허용합니다. 국제화 도메인은 Punycode(xn--...)로 입력하세요. ` +
      `문맥: ...${context}...`,
  );
}

/**
 * PAC 스크립트 소스를 생성한다.
 *
 * @param {object} settings settings.js 의 완전한 설정 객체
 * @returns {string} 순수 ASCII PAC 스크립트 소스
 * @throws {Error} 결과물에 비ASCII 문자가 남아 있으면 (Chrome 이 거부하므로 미리 잡는다)
 */
export function buildPacScript(settings) {
  const { server, bypass } = settings;
  const proxyToken = buildProxyToken(server);
  const { exact, suffix } = splitHostPatterns(bypass.hosts);
  const cidrs = toNumericCidrs(bypass.cidrs);

  const injected = toAsciiJson({
    PROXY: proxyToken,
    EXACT: exact,
    SUFFIX: suffix,
    CIDRS: cidrs,
    PRIVATE: Boolean(bypass.privateNetworks),
    SINGLE_LABEL: Boolean(bypass.singleLabelHosts),
  });

  // ---------------------------------------------------------------------------
  // 여기서부터 PAC 본문. ASCII 만 쓸 수 있으므로 주석도 영어다.
  // ---------------------------------------------------------------------------
  const source = `// Generated by Remote Proxy Router. Do not edit by hand.
// ASCII only: chrome.proxy rejects any non-ASCII byte in pacScript.data.
var CFG = ${injected};

function normalizeHost(host) {
  var h = ('' + host).toLowerCase();
  // Strip brackets from IPv6 literals.
  if (h.charAt(0) === '[') {
    var close = h.indexOf(']');
    h = close > 0 ? h.substring(1, close) : h.substring(1);
  }
  // Strip the trailing dot of a fully qualified name.
  if (h.length > 1 && h.charAt(h.length - 1) === '.') {
    h = h.substring(0, h.length - 1);
  }
  return h;
}

// Parse literal IPv4 only. Returns null for host names.
// We never call dnsResolve(): it would leak the destination to the carrier DNS
// and add latency on an already slow cellular path.
function parseIPv4(host) {
  var parts = host.split('.');
  if (parts.length !== 4) return null;
  var value = 0;
  for (var i = 0; i < 4; i++) {
    var segment = parts[i];
    if (segment.length === 0 || segment.length > 3) return null;
    for (var j = 0; j < segment.length; j++) {
      var code = segment.charCodeAt(j);
      if (code < 48 || code > 57) return null;
    }
    var octet = parseInt(segment, 10);
    if (octet > 255) return null;
    value = (value * 256) + octet;
  }
  return value >>> 0;
}

function inCidr(ip, network, prefix) {
  if (prefix === 0) return true;
  var mask = (0xFFFFFFFF << (32 - prefix)) >>> 0;
  return ((ip & mask) >>> 0) === network;
}

// RFC1918 plus other special-purpose ranges.
function isPrivateIPv4(ip) {
  var a = (ip >>> 24) & 0xFF;
  var b = (ip >>> 16) & 0xFF;
  if (a === 10) return true;                          // 10.0.0.0/8
  if (a === 127) return true;                         // 127.0.0.0/8
  if (a === 172 && b >= 16 && b <= 31) return true;   // 172.16.0.0/12
  if (a === 192 && b === 168) return true;            // 192.168.0.0/16
  if (a === 169 && b === 254) return true;            // 169.254.0.0/16
  if (a === 100 && b >= 64 && b <= 127) return true;  // 100.64.0.0/10 (CGNAT)
  if (a === 0) return true;                           // 0.0.0.0/8
  return false;
}

// IPv6 loopback / link-local / unique-local.
function isPrivateIPv6(host) {
  if (host.indexOf(':') < 0) return false;
  if (host === '::1' || host === '::') return true;
  if (host.indexOf('fe80:') === 0) return true;
  if (host.charAt(0) === 'f') {
    var second = host.charAt(1);
    if (second === 'c' || second === 'd') return true; // fc00::/7
  }
  return false;
}

function endsWithAny(host, suffixes) {
  for (var i = 0; i < suffixes.length; i++) {
    var s = suffixes[i];
    if (host.length >= s.length && host.lastIndexOf(s) === host.length - s.length) {
      return true;
    }
  }
  return false;
}

function matchesAny(host, list) {
  for (var i = 0; i < list.length; i++) {
    if (host === list[i]) return true;
  }
  return false;
}

function FindProxyForURL(url, host) {
  var h = normalizeHost(host);

  // 1) Single-label host (no dot): treat as intranet.
  if (CFG.SINGLE_LABEL && h.indexOf('.') < 0 && h.indexOf(':') < 0) {
    return 'DIRECT';
  }

  // 2) Explicit bypass list (exact match, then suffix match).
  if (matchesAny(h, CFG.EXACT)) return 'DIRECT';
  if (endsWithAny(h, CFG.SUFFIX)) return 'DIRECT';

  // 3) IPv6 literal.
  if (isPrivateIPv6(h)) return 'DIRECT';

  // 4) IPv4 literal: private ranges and user-supplied CIDRs.
  //    192.168.49.0/24 is the phone's Wi-Fi Direct group owner and
  //    10.42.0.0/24 is the tun2proxy virtual NIC. Sending either through the
  //    remote proxy would cut the tethering path itself.
  var ip = parseIPv4(h);
  if (ip !== null) {
    if (CFG.PRIVATE && isPrivateIPv4(ip)) return 'DIRECT';
    for (var i = 0; i < CFG.CIDRS.length; i++) {
      if (inCidr(ip, CFG.CIDRS[i][0], CFG.CIDRS[i][1])) return 'DIRECT';
    }
  }

  // 5) Everything else goes to the remote proxy.
  //    No '; DIRECT' fallback on purpose (fail-closed): with a fallback, a dead
  //    proxy would silently expose the real cellular IP.
  return CFG.PROXY;
}
`;

  // Chrome 이 거부하기 전에 우리가 먼저 잡는다. 원인 위치까지 알려준다.
  return assertPacIsAscii(source);
}
