const posts = {
    list: [
        { file: "/posts/algorithm/ai.html", category: "Algorithm", title: "AI" },
        { file: "/posts/algorithm/algo.html", category: "Algorithm", title: "Algorithm" },
        { file: "/posts/algorithm/book01.html", category: "Algorithm", title: "『알고리즘 도감』" },
        { file: "/posts/algorithm/koreatech.html", category: "Algorithm", title: "jduge.koreatech.ac.kr" },
        { file: "/posts/algorithm/linear_algebra.html", category: "Algorithm", title: "선형대수" },
        { file: "/posts/algorithm/probability.html", category: "Algorithm", title: "확률" },
        
        { file: "/posts/book/001.html", category: "Book", title: "1만 시간의 재발견" },
        { file: "/posts/book/002.html", category: "Book", title: "마음의 탄생" },
        { file: "/posts/book/003.html", category: "Book", title: "생각하는 삶을 위한 철학의 역사" },
        { file: "/posts/book/004.html", category: "Book", title: "쇼펜하우어, 돌이 별이 되는 철학" },
        { file: "/posts/book/005.html", category: "Book", title: "인생의 모든 의미" },
        { file: "/posts/book/009.html", category: "Book", title: "인지 편향" },
        { file: "/posts/book/006.html", category: "Book", title: "지식의 착각" },
        { file: "/posts/book/007.html", category: "Book", title: "키르케고르 실존 극장" },
        { file: "/posts/book/008.html", category: "Book", title: "Gamification by Design" },

        { file: "/posts/dotnet/csharp_library.html", category: "Programming/.NET", title: "C# 라이브러리" },
        { file: "/posts/dotnet/csharp_basic.html", category: "Programming/.NET", title: "C# 시작하기" },
        { file: "/posts/dotnet/wpf_basic.html", category: "Programming/.NET", title: "WPF 시작하기" },
        
        { file: "/posts/db/concept.html", category: "Programming/DB", title: "기본 개념" },
        { file: "/posts/db/mysql.html", category: "Programming/DB", title: "MySQL" },
        { file: "/posts/db/psql_to_sqlite.html", category: "Programming/DB", title: "PostgreSQL → SQLite3 마이그레이션" },
        { file: "/posts/db/psql_admin.html", category: "Programming/DB", title: "PostgreSQL 서버 관리" },
        { file: "/posts/db/psql_programming.html", category: "Programming/DB", title: "PostgreSQL 서버 프로그래밍" },
        { file: "/posts/db/psql_tutorial.html", category: "Programming/DB", title: "PostgreSQL 시작하기" },
        { file: "/posts/db/psql_sql.html", category: "Programming/DB", title: "PostgreSQL SQL 언어" },

        { file: "/posts/front/css.html", category: "Programming/Front", title: "CSS" },
        { file: "/posts/front/html.html", category: "Programming/Front", title: "HTML" },
        { file: "/posts/front/http.html", category: "Programming/Front", title: "HTTP 1.1" },
        { file: "/posts/front/freemarker/built_in.html", category: "Programming/Front/FreeMarker", title: "Built-in 목록 2.3.28" },
        { file: "/posts/front/freemarker/programming_guide.html", category: "Programming/Front/FreeMarker", title: "프로그래밍 가이드 2.3.28" },
        { file: "/posts/front/freemarker/template_guide.html", category: "Programming/Front/FreeMarker", title: "템플릿 작성 가이드 2.3.28" },
        { file: "/posts/front/freemarker/xml_guide.html", category: "Programming/Front/FreeMarker", title: "XML 처리 가이드 2.3.28" },

        { file: "/posts/java/android.html", category: "Programming/Java", title: "Android" },
        { file: "/posts/java/basic.html", category: "Programming/Java", title: "Java 시작하기" },
        { file: "/posts/java/effective_java.html", category: "Programming/Java", title: "『Effective Java』" },
        { file: "/posts/java/java_ee.html", category: "Programming/Java", title: "JavaEE" },
        { file: "/posts/java/javafx.html", category: "Programming/Java", title: "JavaFX" },
        { file: "/posts/java/jni.html", category: "Programming/Java", title: "Java Native Interface" },
        { file: "/posts/java/oop.html", category: "Programming/Java", title: "Java 객체지향" },
        { file: "/posts/java/version.html", category: "Programming/Java", title: "Java 버전별 추가사항" },

        { file: "/posts/java/apache.commons.collections.html", category: "Programming/Java/apache.commons", title: "Apache Commons Collections 4.4" },
        { file: "/posts/java/apache.commons.lang.html", category: "Programming/Java/apache.commons", title: "Apache Commons Lang 3.9" },
        { file: "/posts/java/apache.commons.math.html", category: "Programming/Java/apache.commons", title: "Apache Commons Math 3.6.1" },
        { file: "/posts/java/apache.commons.rng.html", category: "Programming/Java/apache.commons", title: "Apache Commons RNG Core 1.2" },
        { file: "/posts/java/com.sun.nio.sctp.html", category: "Programming/Java/jdk.sctp", title: "com.sun.nio.sctp 12 Since 1.7" },
        { file: "/posts/java/jackson.html", category: "Programming/Java/FasterXML", title: "Jackson 2.10.1" },
        { file: "/posts/java/gson.html", category: "Programming/Java/google", title: "Gson 2.8.6" },
        { file: "/posts/java/guava.html", category: "Programming/Java/google", title: "Guava 23.0" },
        { file: "/posts/java/java.io.html", category: "Programming/Java/java.base", title: "java.io 12 Since 1.0" },
        { file: "/posts/java/java.lang.html", category: "Programming/Java/java.base", title: "java.lang 12 Since 1.0" },
        { file: "/posts/java/java.lang.annotation.html", category: "Programming/Java/java.base", title: "java.lang.annotation 12 Since 1.5" },
        { file: "/posts/java/java.lang.module.html", category: "Programming/Java/java.base", title: "java.lang.module 12 Since 9" },
        { file: "/posts/java/java.lang.ref.html", category: "Programming/Java/java.base", title: "java.lang.ref 12 Since 1.2" },
        { file: "/posts/java/java.lang.reflect.html", category: "Programming/Java/java.base", title: "java.lang.reflect 12 Since 1.1" },
        { file: "/posts/java/java.math.html", category: "Programming/Java/java.base", title: "java.math 12 Since 1.1" },
        { file: "/posts/java/java.net.html", category: "Programming/Java/java.base", title: "java.net 12 Since 1.0" },
        { file: "/posts/java/java.nio.html", category: "Programming/Java/java.base", title: "java.nio 12 Since 1.4" },
        { file: "/posts/java/java.nio.channels.html", category: "Programming/Java/java.base", title: "java.nio.channels 12 Since 1.4" },
        { file: "/posts/java/java.nio.charset.html", category: "Programming/Java/java.base", title: "java.nio.charset 12 Since 1.4" },
        { file: "/posts/java/java.nio.file.html", category: "Programming/Java/java.base", title: "java.nio.file 12 Since 1.7" },
        { file: "/posts/java/java.security.html", category: "Programming/Java/java.base", title: "java.security 12 Since 1.1" },
        { file: "/posts/java/java.text.html", category: "Programming/Java/java.base", title: "java.text 12 Since 1.1" },
        { file: "/posts/java/java.time.html", category: "Programming/Java/java.base", title: "java.time 12 Since 1.8" },
        { file: "/posts/java/java.time.format.html", category: "Programming/Java/java.base", title: "java.time.format 12 Since 1.8" },
        { file: "/posts/java/java.util.html", category: "Programming/Java/java.base", title: "java.util 12 Since 1.0" },
        { file: "/posts/java/java.util.concurrent.html", category: "Programming/Java/java.base", title: "java.util.concurrent 12 Since 1.5" },
        { file: "/posts/java/java.util.concurrent.atomic.html", category: "Programming/Java/java.base", title: "java.util.concurrent.atomic 12 Since 1.5"},
        { file: "/posts/java/java.util.function.html", category: "Programming/Java/java.base", title: "java.util.function 12 Since 1.8"  },
        { file: "/posts/java/java.util.regex.html", category: "Programming/Java/java.base", title: "java.util.regex 12 Since 1.4" },
        { file: "/posts/java/java.util.stream.html", category: "Programming/Java/java.base", title: "java.util.stream 12 Since 1.8" },
        { file: "/posts/java/java.util.zip.html", category: "Programming/Java/java.base", title: "java.util.zip 12 Since 1.1" },
        { file: "/posts/java/javax.crypto.html", category: "Programming/Java/java.base", title: "javax.crypto 12 Since 1.4" },
        { file: "/posts/java/javax.net.html", category: "Programming/Java/java.base", title: "javax.net 12 Since 1.4" },
        { file: "/posts/java/javax.net.ssl.html", category: "Programming/Java/java.base", title: "javax.net.ssl 12 Since 1.4" },
        { file: "/posts/java/javax.annotation.processing.html", category: "Programming/Java/java.compiler", title: "Annotation Processing API" },
        { file: "/posts/java/lombok.html", category: "Programming/Java", title: "lombok 1.18.10" },
        { file: "/posts/java/logback.html", category: "Programming/Java", title: "Logback with SLF4J" },

        { file: "/posts/javascript/basic.html", category: "Programming/JavaScript", title: "코어 JavaScript" },
        { file: "/posts/javascript/basic2.html", category: "Programming/JavaScript", title: "브라우저 JavaScript" },
        { file: "/posts/javascript/jquery.html", category: "Programming/JavaScript", title: "jQuery" },

        { file: "/posts/python/basic.html", category: "Programming/Python", title: "Python 3.8 시작하기" },
        { file: "/posts/python/data_model.html", category: "Programming/Python", title: "Python 3.8 데이터 모델" },
        { file: "/posts/python/built_in_function.html", category: "Programming/Python", title: "Python Built-in Functions 3.8" },
        { file: "/posts/python/built_in_constant.html", category: "Programming/Python", title: "Python Built-in Constants 3.8" },
        { file: "/posts/python/built_in_type.html", category: "Programming/Python", title: "Python Built-in Types 3.8" },
        { file: "/posts/python/built_in_exception.html", category: "Programming/Python", title: "Python Built-in Exceptions 3.8" },
        { file: "/posts/python/string.html", category: "Programming/Python/Library", title: "Lib/string : 문자열 공통 연산" },
        { file: "/posts/python/re.html", category: "Programming/Python/Library", title: "Lib/re : 정규표현식" },
        { file: "/posts/python/textwrap.html", category: "Programming/Python/Library", title: "Lib/textwrap : 텍스트 정돈" },
        { file: "/posts/python/unicodedata.html", category: "Programming/Python/Library", title: "Lib/unicodedata : 유니코드 database 표준" },
        { file: "/posts/python/struct.html", category: "Programming/Python/Library", title: "Lib/struct : 이진 데이터 패킹/언패킹" },
        { file: "/posts/python/datetime.html", category: "Programming/Python/Library", title: "Lib/datetime : 단순 시간 표현" },
        { file: "/posts/python/calendar.html", category: "Programming/Python/Library", title: "Lib/calendar : 달력 연산" },
        { file: "/posts/python/collections.html", category: "Programming/Python/Library", title: "Lib/collections : 컨테이너" },
        { file: "/posts/python/collections.abc.html", category: "Programming/Python/Library", title: "Lib/collections.abc : 컨테이너 ABC" },
        { file: "/posts/python/pandas.html", category: "Programming/Python/Library", title: "3rd/pandas : 데이터 처리" },

        { file: "/posts/project/wpf_data_tool.html", category: "Project", title: "C#.NET, WPF - 데이터 작업 툴" },
        { file: "/posts/project/browser_code_snippet.html", category: "Project", title: "JavaScript - 브라우저 코드 조각" },
        { file: "/posts/project/browser_script.html", category: "Project", title: "JavaScript - 브라우저 매크로 스크립트" },
        
        { file: "/posts/tip/snippets.html", category: "Tip", title: "Code Snippets" },
        { file: "/posts/tip/error.html", category: "Tip", title: "Exceptions + Errors" },
        { file: "/posts/tip/tip.html", category: "Tip", title: "사소한 팁" },
        { file: "/posts/tip/aws.html", category: "Tip", title: "AWS" },
        { file: "/posts/tip/centos.html", category: "Tip", title: "CentOS" },
        { file: "/posts/tip/docker.html", category: "Tip", title: "Docker" },
        { file: "/posts/tip/eclipse.html", category: "Tip", title: "Eclipse" },
        { file: "/posts/tip/fp.html", category: "Tip", title: "FP; Functional Programming" },
        { file: "/posts/tip/git.html", category: "Tip", title: "Git" },
        { file: "/posts/tip/tomcat.html", category: "Tip", title: "tomcat" },
        { file: "/posts/tip/psql.html", category: "Tip", title: "psql" },
        { file: "/posts/tip/refactoring.html", category: "Tip", title: "디자인 패턴 + 리팩터링" },
        { file: "/posts/tip/rpi.html", category: "Tip", title: "Raspberry Pi 3 + OpenCV(python)" },
        { file: "/posts/tip/unity.html", category: "Tip", title: "Unity : 작성 중지" },
        { file: "/posts/tip/vi.html", category: "Tip", title: "vi" },
    ],
    hash: {},
    codes: {},
};

/*
<button class="btn-code" path="Repositories/Eclipse" lan="java">예시 코드 »
<button class="w3-btn w3-round w3-round-xxlarge w3-small w3-green" onclick="">실행 »
<a class="w3-btn w3-round w3-round-xxlarge w3-small w3-green" target="_blank" href="">
<a class="w3-btn w3-round w3-round-xxlarge w3-small w3-green" href="javascript:;">
<img class="w3-round" src="imgs/">
 */