plugins {
    id 'java'
    id 'eclipse-wtp'
    id 'war'
}

group = 'io.github.donggi'
version = '0.0.1'
sourceCompatibility = JavaVersion.VERSION_25

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

eclipse {
    project.natures "org.springsource.ide.eclipse.gradle.core.nature"
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework:spring-webmvc:7.0.8'
	implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
	implementation 'org.slf4j:slf4j-api:2.0.16'
	implementation 'org.slf4j:slf4j-simple:2.0.16'
	implementation 'ch.qos.logback:logback-classic:1.5.16'
	implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
	implementation 'jakarta.validation:jakarta.validation-api:3.1.0Final'
	implementation 'org.hibernate.validator:hibernate-validator:6.1.5.Final'
	providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'
	providedCompile 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:4.0.0'
	providedCompile 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
	testImplementation 'junit:junit:4.13.2'
}