
buildscript {
    ext {
        lombokVersion = '1.18.36'
    }

    repositories {
        mavenCentral()
        maven { url = uri("https://plugins.gradle.org/m2/") }
        gradlePluginPortal()
    }
}

allprojects {
    group = 'io.github.donggi.annotation'
    version = ''
    description = ""
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    compileJava {
        options.encoding = 'UTF-8'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }

    repositories {
        mavenCentral()
        mavenLocal()
        gradlePluginPortal()
    }

    dependencies {
        // lombok
        compileOnly "org.projectlombok:lombok:1.18.36"
        testCompileOnly "org.projectlombok:lombok:1.18.36"
        annotationProcessor "org.projectlombok:lombok:1.18.36"
        testAnnotationProcessor "org.projectlombok:lombok:1.18.36"

        testImplementation 'junit:junit:4.13.2'
    }
}
