plugins {
    id 'java'
}

repositories {
    jcenter()
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation 'io.netty:netty-all:4.1.51.Final'
    implementation 'org.slf4j:slf4j-api:1.7.30'
	implementation 'org.slf4j:slf4j-simple:1.7.30'
	compileOnly 'org.projectlombok:lombok:1.18.12'
	annotationProcessor 'org.projectlombok:lombok:1.18.12'
	testImplementation 'junit:junit:4.12'
}
