plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation 'io.netty:netty-all:4.1.115.Final'
    implementation 'org.slf4j:slf4j-api:2.0.16'
	implementation 'org.slf4j:slf4j-simple:2.0.16'
	compileOnly 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
	testImplementation 'junit:junit:4.13.2'
}
