plugins {
    id 'java'
    id 'eclipse-wtp'
    id 'war'
}

group = 'io.github.donggi'
version = '0.0.1'
sourceCompatibility = JavaVersion.VERSION_25

eclipse {
    project.natures "org.springsource.ide.eclipse.gradle.core.nature"
}

repositories {
	mavenCentral()
}

dependencies {
	providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'
	providedCompile 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:4.0.0'
}
