const recentChangedPosts = `
A	pugs/book/010.pug
A	pugs/infra/k8s.pug
A	pugs/project/ip2country.pug
A	pugs/topic/frp.pug
M	pugs/algorithm/acmicpc.pug
M	pugs/daily_life/house.pug
M	pugs/daily_life/labor.pug
M	pugs/infra/aws.pug
M	pugs/language/javascript/basic2.pug
M	pugs/language/javascript/node.pug
M	pugs/algorithm/mcs.pug
M	pugs/algorithm/mcs.pug
M	pugs/infra/db/redis.pug
M	pugs/infra/nginx.pug
M	pugs/language/javascript/node.pug
A	pugs/topic/docker_mailserver.pug
M	pugs/infra/nginx.pug
M	pugs/algorithm/acmicpc.pug
M	pugs/infra/linux.pug
M	pugs/algorithm/overview.pug
M	pugs/infra/db/psql_programming.pug
M	pugs/infra/web/network.pug
M	pugs/language/javascript/node.pug
A	pugs/algorithm/acmicpc.pug
M	pugs/algorithm/overview.pug
M	pugs/infra/db/mysql.pug
M	pugs/infra/db/psql_programming.pug
M	pugs/language/jvm/android.pug
M	pugs/topic/rpi.pug
M	pugs/language/jvm/javafx.pug
M	pugs/language/jvm/logback.pug
M	pugs/project/snippets.pug
M	pugs/algorithm/overview.pug
M	pugs/algorithm/overview.pug
M	pugs/infra/aws.pug
M	pugs/infra/gradle.pug
M	pugs/language/jvm/java.base.pug
M	pugs/project/snippets.pug
M	pugs/project/snippets.pug
M	pugs/infra/aws.pug
M	pugs/infra/git.pug
M	pugs/project/snippets.pug
D	pugs/algorithm/koreatech/1003.pug
D	pugs/algorithm/koreatech/1008.pug
D	pugs/algorithm/koreatech/1010.pug
D	pugs/algorithm/koreatech/1011.pug
D	pugs/algorithm/koreatech/1018.pug
D	pugs/algorithm/koreatech/1034.pug
D	pugs/algorithm/koreatech/1048.pug
D	pugs/algorithm/koreatech/1095.pug
M	pugs/algorithm/koreatech/1003.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
M	pugs/daily_life/death.pug
`;
