const recentChangedPosts = `
M	posts/algorithm/koreatech/1003.html
M	posts/infra/aws.html
M	posts/algorithm/mcs.html
M	posts/daily_life/death.html
M	posts/algorithm/ai.html
M	posts/algorithm/koreatech/1003.html
M	posts/algorithm/koreatech/1008.html
M	posts/algorithm/koreatech/1010.html
M	posts/algorithm/koreatech/1011.html
M	posts/algorithm/koreatech/1018.html
M	posts/algorithm/koreatech/1034.html
M	posts/algorithm/koreatech/1048.html
M	posts/algorithm/koreatech/1095.html
M	posts/algorithm/linear_algebra.html
M	posts/algorithm/mcs.html
M	posts/algorithm/overview.html
M	posts/algorithm/probability.html
M	posts/book/001.html
M	posts/book/002.html
M	posts/book/003.html
M	posts/book/004.html
M	posts/book/005.html
M	posts/book/006.html
M	posts/book/007.html
M	posts/book/008.html
M	posts/book/009.html
M	posts/daily_life/baron.html
M	posts/daily_life/business.html
M	posts/daily_life/car.html
M	posts/daily_life/death.html
M	posts/daily_life/house.html
M	posts/daily_life/labor.html
M	posts/daily_life/stock.html
M	posts/infra/aws.html
M	posts/infra/cicd.html
M	posts/infra/db/RabbitMQ.html
M	posts/infra/db/concept.html
M	posts/infra/db/mongodb.html
M	posts/infra/db/mysql.html
M	posts/infra/db/psql_admin.html
M	posts/infra/db/psql_programming.html
M	posts/infra/db/psql_sql.html
M	posts/infra/db/psql_to_sqlite.html
M	posts/infra/db/psql_tutorial.html
M	posts/infra/db/redis.html
M	posts/infra/docker.html
M	posts/infra/elk.html
M	posts/infra/git.html
M	posts/infra/gradle.html
M	posts/infra/linux.html
M	posts/infra/nginx.html
M	posts/infra/sdkman.html
M	posts/infra/web/css.html
M	posts/infra/web/html.html
M	posts/infra/web/network.html
M	posts/infra/web/oauth.html
M	posts/language/.net/csharp_basic.html
M	posts/language/.net/csharp_library.html
M	posts/language/.net/wpf_basic.html
M	posts/language/javascript/basic.html
M	posts/language/javascript/basic2.html
M	posts/language/javascript/jquery.html
M	posts/language/javascript/node.html
M	posts/language/jvm/android.html
M	posts/language/jvm/apache.commons.collections.html
M	posts/language/jvm/apache.commons.lang.html
M	posts/language/jvm/apache.commons.math.html
M	posts/language/jvm/apache.commons.rng.html
M	posts/language/jvm/basic.html
M	posts/language/jvm/com.sun.nio.sctp.html
M	posts/language/jvm/effective_java.html
M	posts/language/jvm/freemarker_built_in.html
M	posts/language/jvm/freemarker_programming_guide.html
M	posts/language/jvm/freemarker_template_guide.html
M	posts/language/jvm/freemarker_xml_guide.html
M	posts/language/jvm/groovy.html
M	posts/language/jvm/gson.html
M	posts/language/jvm/guava.html
M	posts/language/jvm/jackson.html
M	posts/language/jvm/java.base.html
M	posts/language/jvm/java.net.http.html
M	posts/language/jvm/java_ee.html
M	posts/language/jvm/javafx.html
M	posts/language/jvm/javax.annotation.processing.html
M	posts/language/jvm/jni.html
M	posts/language/jvm/jpa.html
M	posts/language/jvm/logback.html
M	posts/language/jvm/lombok.html
M	posts/language/jvm/netty.html
M	posts/language/jvm/performance.html
M	posts/language/jvm/spring_framework.html
M	posts/language/jvm/spring_reactive.html
M	posts/language/jvm/spring_servlet.html
M	posts/language/jvm/version.html
M	posts/language/python/basic.html
M	posts/language/python/built_in_constant.html
M	posts/language/python/built_in_exception.html
M	posts/language/python/built_in_function.html
M	posts/language/python/built_in_type.html
M	posts/language/python/data_model.html
M	posts/language/python/pandas.html
M	posts/language/python/persistence.html
M	posts/language/python/standard.html
M	posts/language/ruby/basic.html
M	posts/project/cctv.html
M	posts/project/error.html
M	posts/project/igaworks_push.html
M	posts/project/privacy.html
M	posts/project/reminder.html
M	posts/project/sf.html
M	posts/project/snippets.html
M	posts/project/tip.html
M	posts/project/wpf_data_tool.html
M	posts/topic/demo3.html
M	posts/topic/fp.html
M	posts/topic/interview.html
M	posts/topic/quantum_computer.html
M	posts/topic/refactoring.html
M	posts/topic/rpi.html
M	posts/topic/tomcat.html
M	posts/topic/unity.html
M	posts/infra/nginx.html
M	posts/algorithm/mcs.html
M	posts/daily_life/stock.html
M	posts/algorithm/mcs.html
A	posts/daily_life/baron.html
M	posts/project/privacy.html
M	posts/algorithm/overview.html
M	posts/daily_life/car.html
A	posts/daily_life/death.html
M	posts/daily_life/house.html
A	posts/daily_life/stock.html
M	posts/infra/db/psql_tutorial.html
M	posts/infra/linux.html
M	posts/infra/nginx.html
M	posts/infra/web/css.html
M	posts/infra/web/network.html
M	posts/project/error.html
M	posts/project/snippets.html
M	posts/project/tip.html
M	posts/algorithm/mcs.html
M	posts/daily_life/house.html
A	posts/daily_life/business.html
A	posts/daily_life/car.html
A	posts/daily_life/house.html
A	posts/daily_life/labor.html
A	posts/daily_life/link.html
M	posts/infra/aws.html
M	posts/infra/elk.html
M	posts/language/jvm/basic.html
M	posts/infra/db/RabbitMQ.html
A	posts/infra/elk.html
M	posts/language/jvm/spring_framework.html
M	posts/infra/db/RabbitMQ.html
M	posts/project/error.html
M	posts/infra/db/RabbitMQ.html
M	posts/language/jvm/basic.html
M	posts/infra/db/RabbitMQ.html
A	posts/infra/db/RabbitMQ.html
M	posts/project/cctv.html
M	posts/algorithm/ai.html
M	posts/project/cctv.html
M	posts/project/cctv.html
A	posts/project/privacy.html
M	posts/project/cctv.html
`;
