const recentChangedPosts = `
A	pugs/book/024.pug
A	pugs/book/025.pug
A	pugs/book/026.pug
A	pugs/book/027.pug
M	pugs/infra/aws.pug
A	pugs/book/023.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
M	pugs/book/022.pug
M	pugs/book/022.pug
M	pugs/infra/aws.pug
M	pugs/infra/linux.pug
M	pugs/book/022.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
M	pugs/book/020.pug
A	pugs/book/021.pug
A	pugs/book/022.pug
M	pugs/daily_life/stock.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
A	pugs/book/020.pug
M	pugs/infra/aws.pug
M	pugs/infra/linux.pug
M	pugs/algorithm/mcs.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
M	pugs/algorithm/overview.pug
M	pugs/algorithm/mcs.pug
M	pugs/daily_life/house.pug
M	pugs/algorithm/overview.pug
M	pugs/book/019.pug
M	pugs/infra/aws.pug
M	pugs/project/tip.pug
M	pugs/algorithm/mcs.pug
M	pugs/book/019.pug
M	pugs/infra/db/mongodb.pug
M	pugs/infra/docker.pug
M	pugs/infra/linux.pug
M	pugs/language/ruby/basic.pug
M	pugs/infra/aws.pug
M	pugs/algorithm/mcs.pug
M	pugs/book/018.pug
A	pugs/book/019.pug
M	pugs/algorithm/mcs.pug
A	pugs/book/018.pug
M	pugs/infra/aws.pug
M	pugs/language/.net/csharp_basic.pug
D	pugs/language/.net/csharp_library.pug
M	pugs/language/.net/wpf_basic.pug
M	pugs/infra/web/network.pug
M	pugs/language/.net/csharp_basic.pug
M	pugs/book/017.pug
M	pugs/infra/aws.pug
M	pugs/language/.net/csharp_basic.pug
A	pugs/book/016.pug
A	pugs/book/017.pug
M	pugs/infra/aws.pug
`;
